repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2048"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-alpha.1
    hooks:
      - id: eslint
        additional_dependencies: ["eslint@8.56.0"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
